#! /bin/bash
# generated by utils/collect_git_remote_add_recusively.sh

cd ../boost ; git remote add manctl git://github.com/manctl/boost.git
cd ../boost ; git remote add ryppl git://github.com/ryppl/boost-svn.git
cd ../linenoise ; git remote add alonbl git://github.com/alonbl/linenoise.git
cd ../linenoise ; git remote add dvirsky git://github.com/dvirsky/linenoise.git
cd ../linenoise ; git remote add leonerd git://github.com/leonerd/linenoise.git
cd ../linenoise ; git remote add msteveb git://github.com/msteveb/linenoise.git
cd ../linenoise ; git remote add tadmarshall git://github.com/tadmarshall/linenoise.git
cd ../linenoise ; git remote add trairia git://github.com/trairia/linenoise.git
cd ../linenoise ; git remote add vext01 git://github.com/vext01/linenoise.git
cd ../pthread-win32 ; git remote add capttofu git://github.com/CaptTofu/Pthreads-win32.git
cd ../pthread-win32 ; git remote add coapp git://github.com/coapp-packages/pthreads-win32.git
cd ../pthread-win32 ; git remote add kakaroto git://github.com/kakaroto/pthread-embeded.git
cd ../pthread-win32 ; git remote add membase git://github.com/membase/pthreads-win.git
cd ../pthread-win32 ; git remote add vfr git://github.com/VFR-maniac/pthreads-win32.git
